spring:
  application:
    name: api-gateway
  boot:
    webflux:
      base-path: /api

server:
  port: 8080
  servlet:
    context-path: /api

grpc:
  orchestrator:
    host: orchestrator
    port: 50054

logging:
  level:
    org.example: DEBUG
